---
- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    state: present
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy mysql
  community.kubernetes.helm:
    state: "{{ mysql_state }}"
    name: mysql
    namespace: "{{ mysql_namespace }}"
    create_namespace: true
    chart_ref: bitnami/mysql
    chart_version: 9.1.7
    values: "{{ lookup('template', 'mysql_values.yml.j2') | from_yaml | combine(mysql_chart_values, recursive=True) }}"
    wait: yes
    wait_timeout: 10m
  register: mysql_installed

- name: Deploy phpmyadmin
  community.kubernetes.helm:
    state: "{{ mysql_state }}"
    name: phpmyadmin
    namespace: "{{ mysql_namespace }}"
    create_namespace: true
    chart_ref: bitnami/phpmyadmin
    chart_version: 10.1.9
    values: "{{ lookup('template', 'phpmyadmin_values.yml.j2') | from_yaml | combine(phpmyadmin_chart_values, recursive=True) }}"
    wait: yes
    wait_timeout: 10m
  register: phpmyadmin_installed
